-- Run this entire file once in Supabase: SQL Editor > New query > Run.
create table if not exists public.equipment (
  id bigint generated by default as identity primary key,
  equipment_name text not null check (length(trim(equipment_name)) > 0),
  category text not null,
  asset_code text unique not null,
  condition text not null default 'Good' check (condition in ('Good', 'Fair', 'For Repair')),
  availability text not null default 'Available' check (availability in ('Available', 'Borrowed')),
  created_at timestamptz not null default now()
);

create table if not exists public.borrow_transactions (
  id bigint generated by default as identity primary key,
  equipment_id bigint not null references public.equipment(id),
  borrower_name text not null check (length(trim(borrower_name)) > 0),
  borrower_type text not null check (borrower_type in ('Student', 'Faculty', 'Staff')),
  department text not null,
  date_borrowed date not null default current_date,
  due_date date not null check (due_date >= date_borrowed),
  date_returned date,
  status text not null default 'Borrowed' check (status in ('Borrowed', 'Returned', 'Overdue')),
  user_id uuid not null references auth.users(id),
  created_at timestamptz not null default now()
);

alter table public.equipment enable row level security;
alter table public.borrow_transactions enable row level security;

create policy "Authenticated users can manage equipment" on public.equipment
  for all to authenticated using (true) with check (true);
create policy "Authenticated users can manage transactions" on public.borrow_transactions
  for all to authenticated using (true) with check (true);

-- Optional sample data for demonstration.
insert into public.equipment (equipment_name, category, asset_code, condition, availability)
values
  ('Epson Projector', 'Projector', 'PROJ-001', 'Good', 'Available'),
  ('Acer Laptop', 'Laptop', 'LAP-001', 'Good', 'Available'),
  ('Canon Camera', 'Camera', 'CAM-001', 'Fair', 'Available')
on conflict (asset_code) do nothing;
